services:
  - type: web
    name: mvp-bonus-tma
    env: node
    plan: free
    rootDir: .
    buildCommand: |
      npm install --prefix client
      npm run build --prefix client
      npm install --prefix server
    startCommand: npm start --prefix server
    envVars:
      - key: PORT
        value: 3001
      - key: CLIENT_ORIGINS
        value: https://mvp-bonus-tma.onrender.com
      - key: ADMIN_TG_IDS
        value: 1300839309
      - key: BOT_TOKEN
        value: 8504812083:AAHLX2yxAmYJmw7ONvVwFxnLJ3PZvtGFx3M
